//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirthRegister
    {
        public int ID { get; set; }
        public int StudentID_FK { get; set; }
        public System.DateTime Registered { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
