//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTAG
    {
        public int ID { get; set; }
        public int TagID_FK { get; set; }
        public int Student_FK { get; set; }
        public bool Enabled { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
