//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagRecorder
    {
        public int ID { get; set; }
        public string TagID { get; set; }
        public System.DateTime DateTimeRegister { get; set; }
        public int MysqlID { get; set; }
        public bool SMS { get; set; }
        public Nullable<bool> type { get; set; }
        public bool enables { get; set; }
    }
}
